# Generated by Django 5.2.6 on 2025-09-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
