# Generated by Django 5.2.6 on 2025-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_content_order_alter_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
