# Generated by Django 5.2.6 on 2025-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_topic_order_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
