# Generated by Django 5.2.6 on 2025-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_language_name_en_language_name_ru_language_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='code_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='code_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='code_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
