# Generated by Django 5.2.6 on 2025-09-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_content_code_en_content_code_ru_content_code_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='code_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='code_ru',
        ),
        migrations.RemoveField(
            model_name='content',
            name='code_uz',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text_uz',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_uz',
        ),
    ]
